[package]
name = "resize_jpeg"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
edition = "2018"

[dependencies]
gio = { version = "0.14", features = ["v2_62"] }
glib = { version = "0.14", features = ["v2_62"] }
gtk = { version = "0.14", features = ["v3_24_9"] }
rayon = "1.4"
